package frc.robot.elevator;

public enum ElevatorState {
  UNTUNED(0),
  STOWED(0),
  PRE_MATCH_HOMING(0),
  MID_MATCH_HOMING(0),

  INTAKING_CORAL_STATION_BACK(10.5),
  INTAKING_CORAL_STATION_FRONT(3),

  INTAKING_CORAL_STATION_BACK_PROCESSOR_SIDE(10.5),
  INTAKING_CORAL_STATION_FRONT_PROCESSOR_SIDE(3),

  GROUND_CORAL_INTAKE(0),
  GROUND_ALGAE_INTAKE(10.2),

  ALGAE_DISLODGE_L2(UNTUNED),
  ALGAE_DISLODGE_L3(UNTUNED),
  ALGAE_INTAKE_L2(10.0),
  ALGAE_INTAKE_L3(25.0),

  NET(58.0),
  PROCESSOR(0),

  CORAL_L1_PLACE(2.0),
  CORAL_L1_RELEASE(0.0),

  // Approach coral positions (maximum height without tipping)
  CORAL_L2_APPROACH(7.5),
  CORAL_L3_APPROACH(20.0),
  CORAL_L4_APPROACH(20.0),

  // Centered coral positions
  CORAL_CENTERED_L2_LINEUP(8.75),
  CORAL_CENTERED_L2_PLACE(7.0),
  CORAL_CENTERED_L2_RELEASE(0.0),

  CORAL_CENTERED_L3_LINEUP(27.0),
  CORAL_CENTERED_L3_PLACE(22.5),
  CORAL_CENTERED_L3_RELEASE(8.0),

  CORAL_CENTERED_L4_RAISE_WRIST(57),
  CORAL_CENTERED_L4_LINEUP(57),
  CORAL_CENTERED_L4_PLACE(45.6),
  CORAL_CENTERED_L4_RELEASE(40.0),

  // Displaced coral positions
  CORAL_DISPLACED_L2_LINEUP(7.5),
  CORAL_DISPLACED_L2_PLACE(5.5),
  CORAL_DISPLACED_L2_RELEASE(0.0),

  CORAL_DISPLACED_L3_LINEUP(22.5),
  CORAL_DISPLACED_L3_PLACE(19.0),
  CORAL_DISPLACED_L3_RELEASE(8.0),

  CORAL_DISPLACED_L4_RAISE_WRIST(52.5),
  CORAL_DISPLACED_L4_LINEUP(52.5),
  CORAL_DISPLACED_L4_PLACE(42.5),
  CORAL_DISPLACED_L4_RELEASE(40.0),

  UNJAM(0),
  CLIMBING(0),

  COLLISION_AVOIDANCE(0);

  public final double height;

  private ElevatorState(double height) {
    this.height = height;
  }

  private ElevatorState(ElevatorState other) {
    this(other.height);
  }
}
