package frc.robot.wrist;

public enum WristState {
  IDLE(0.0),
  UNJAM(0.0),
  PRE_MATCH_HOMING(0.0),

  CORAL_SCORE_LINEUP_L1(0.0),
  CORAL_SCORE_LINEUP_L2(0.0),
  CORAL_SCORE_LINEUP_L3(0.0),
  CORAL_SCORE_LINEUP_L4(0.0),

  CORAL_SCORE_PLACING_L1(0.0),
  CORAL_SCORE_PLACING_L2(0.0),
  CORAL_SCORE_PLACING_L3(0.0),
  CORAL_SCORE_PLACING_L4(0.0),

  CORAL_INTAKE_L1(0.0),
  CORAL_INTAKE_L2(0.0),
  CORAL_INTAKE_L3(0.0),
  CORAL_INTAKE_L4(0.0),

  ALGAE_INTAKE_L2(0.0),
  ALGAE_INTAKE_L3(0.0),

  ALGAE_FORWARD_NET(0.0),
  ALGAE_BACKWARD_NET(0.0),
  ALGAE_PROCESSOR(0.0),

  DISLODGE_L2_LOW(0.0),
  DISLODGE_L2_HIGH(0.0),
  DISLODGE_L3_LOW(0.0),
  DISLODGE_L3_HIGH(0.0),

  INTAKING_CORAL_STATION(0.0),
  GROUND_CORAL_INTAKE(0.0),
  GROUND_ALGAE_INTAKE(0.0),

  COLLISION_AVOIDANCE(0);

  public final double angle;

  WristState(double angle) {
    this.angle = angle;
  }
}
