package frc.robot.wrist;

public enum WristState {
  STOWED(40.0),
  UNJAM(0.0),
  PRE_MATCH_HOMING(0.0),
  MID_MATCH_HOMING(0.0),

  CORAL_SCORE_PLACING_L1(13.0),
  CORAL_SCORE_RELEASE_L1(13.0),

  CORAL_SCORE_LINEUP_L2(20.0),
  CORAL_SCORE_PLACING_L2(28.0),
  CORAL_SCORE_RELEASE_L2(55.0),

  CORAL_SCORE_LINEUP_L3(20.0),
  CORAL_SCORE_PLACING_L3(28.0),
  CORAL_SCORE_RELEASE_L3(55.0),

  CORAL_SCORE_LINEUP_L4(16.2),
  CORAL_SCORE_PLACING_L4(12.2),
  CORAL_SCORE_RELEASE_L4(50.0),

  ALGAE_INTAKE_L2(0.0),
  ALGAE_INTAKE_L3(0.0),

  ALGAE_FORWARD_NET(60.0),
  ALGAE_BACKWARD_NET(159.0),
  ALGAE_PROCESSOR(0.0),

  DISLODGE_L2_LOW(0.0),
  DISLODGE_L2_HIGH(0.0),
  DISLODGE_L3_LOW(0.0),
  DISLODGE_L3_HIGH(0.0),

  GROUND_CORAL_INTAKE(-82.3),
  GROUND_ALGAE_INTAKE(-82.3),

  INTAKING_CORAL_STATION_BACK(180.0),
  INTAKING_CORAL_STATION_FRONT(65.0),

  COLLISION_AVOIDANCE(0);

  public final double angle;

  WristState(double angle) {
    this.angle = angle;
  }
}
