package frc.robot.intake;

public enum IntakeState {
  IDLE_NO_GP,
  IDLE_W_ALGAE,
  IDLE_W_CORAL,
  INTAKING_ALGAE,
  INTAKING_CORAL,
  SCORE_ALGAE_NET,
  SCORE_ALGAE_PROCESSOR,
  SCORE_CORAL,
  OUTTAKING;
}
