package frc.robot.arm;

public enum ArmState {
  UNTUNED(0),

  CLAW_EMPTY_DEPLOY_EMPTY(0),
  CLAW_EMPTY_DEPLOY_CORAL(0),
  CLAW_ALGAE_DEPLOY_CORAL(0),
  CLAW_ALGAE_DEPLOY_EMPTY(0),

  UNJAM(UNTUNED),
  PRE_MATCH_HOMING(0.0),
  MID_MATCH_HOMING(0.0),

  CORAL_SCORE_PLACING_L1(0.0),
  CORAL_SCORE_RELEASE_L1(0.0),

  // L1 scoring with groud intaek
  CORAL_L1_DEPLOY_PREPARE_CLAW_ALGAE(UNTUNED),
  CORAL_L1_DEPLOY_PREPARE_CLAW_EMPTY(UNTUNED),
  CORAL_L1_DEPLOY_SCORE_CLAW_ALGAE(UNTUNED),
  CORAL_L1_DEPLOY_SCORE_CLAW_EMPTY(UNTUNED),
  // Left coral positions

  CORAL_SCORE_LEFT_LINEUP_L2(24.0),
  CORAL_SCORE_LEFT_RELEASE_L2(4.0),

  CORAL_SCORE_LEFT_LINEUP_L3(24.0),
  CORAL_SCORE_LEFT_RELEASE_L3(4.0),

  CORAL_SCORE_LEFT_LINEUP_L4(8.0),
  CORAL_SCORE_LEFT_RELEASE_L4(0.0),

  // Right coral positions
  CORAL_SCORE_RIGHT_LINEUP_L2(15.0),
  CORAL_SCORE_RIGHT_RELEASE_L2(0.0),

  CORAL_SCORE_RIGHT_LINEUP_L3(15.0),
  CORAL_SCORE_RIGHT_RELEASE_L3(0.0),

  CORAL_SCORE_RIGHT_LINEUP_L4(5.0),
  CORAL_SCORE_RIGHT_RELEASE_L4(0.0),

  // Handoffs
  CORAL_L1_HANDOFF(UNTUNED),
  CORAL_L2_HANDOFF(UNTUNED),
  CORAL_L3_HANDOFF(UNTUNED),
  CORAL_L4_HANDOFF(UNTUNED),

  // Algae positions
  ALGAE_INTAKE_L2_DEPLOY_EMPTY(15.0),
  ALGAE_INTAKE_L3_DEPLOY_EMPTY(16.0),
  ALGAE_INTAKE_L2_DEPLOY_CORAL(15.0),
  ALGAE_INTAKE_L3_DEPLOY_CORAL(16.0),
  ALGAE_INTAKE_FLOOR_DEPLOY_EMPTY(-54.0),
  ALGAE_INTAKE_FLOOR_DEPLOY_CORAL(-54.0),

  ALGAE_NET_LEFT_WAITING_DEPLOY_EMPTY(UNTUNED),
  ALGAE_NET_LEFT_RELEASE_DEPLOY_EMPTY(UNTUNED),
  ALGAE_NET_LEFT_WAITING_DEPLOY_CORAL(UNTUNED),
  ALGAE_NET_LEFT_RELEASE_DEPLOY_CORAL(UNTUNED),

  ALGAE_NET_RIGHT_WAITING_DEPLOY_EMPTY(UNTUNED),
  ALGAE_NET_RIGHT_RELEASE_DEPLOY_EMPTY(UNTUNED),
  ALGAE_NET_RIGHT_WAITING_DEPLOY_CORAL(UNTUNED),
  ALGAE_NET_RIGHT_RELEASE_DEPLOY_CORAL(UNTUNED),
  ALGAE_PROCESSOR(-10.0),

  COLLISION_AVOIDANCE(0.0),
  CLIMBING(60.0),

  SMART_STOW_1(100.0);

  public final double angle;

  ArmState(double angle) {
    this.angle = angle;
  }

  ArmState(ArmState other) {
    this(other.angle);
  }
}
