package frc.robot.arm;

public enum ArmState {
  UNTUNED(0),

  CLAW_EMPTY(UNTUNED),

  UNJAM(UNTUNED),
  PRE_MATCH_HOMING(UNTUNED),
  MID_MATCH_HOMING(UNTUNED),

  // Left coral positions
  CORAL_SCORE_LEFT_PLACING_L1(UNTUNED),
  CORAL_SCORE_LEFT_RELEASE_L1(UNTUNED),

  CORAL_SCORE_LEFT_LINEUP_L2(UNTUNED),
  CORAL_SCORE_LEFT_RELEASE_L2(UNTUNED),

  CORAL_SCORE_LEFT_LINEUP_L3(UNTUNED),
  CORAL_SCORE_LEFT_RELEASE_L3(UNTUNED),

  CORAL_SCORE_LEFT_LINEUP_L4(UNTUNED),
  CORAL_SCORE_LEFT_RELEASE_L4(UNTUNED),

  // Right coral positions
  CORAL_SCORE_RIGHT_PLACING_L1(UNTUNED),
  CORAL_SCORE_RIGHT_RELEASE_L1(UNTUNED),

  CORAL_SCORE_RIGHT_LINEUP_L2(UNTUNED),
  CORAL_SCORE_RIGHT_RELEASE_L2(UNTUNED),

  CORAL_SCORE_RIGHT_LINEUP_L3(UNTUNED),
  CORAL_SCORE_RIGHT_RELEASE_L3(UNTUNED),

  CORAL_SCORE_RIGHT_LINEUP_L4(UNTUNED),
  CORAL_SCORE_RIGHT_RELEASE_L4(UNTUNED),

  // Handoffs
  CORAL_HANDOFF(UNTUNED),

  // Algae positions
  ALGAE_INTAKE_L2(UNTUNED),
  ALGAE_INTAKE_L3(UNTUNED),
  ALGAE_INTAKE_FLOOR(UNTUNED),

  ALGAE_NET_LEFT_WAITING(UNTUNED),
  ALGAE_NET_LEFT_RELEASE(UNTUNED),

  ALGAE_NET_RIGHT_WAITING(UNTUNED),
  ALGAE_NET_RIGHT_RELEASE(UNTUNED),

  ALGAE_PROCESSOR(UNTUNED),

  COLLISION_AVOIDANCE(UNTUNED),
  CLIMBING(UNTUNED);

  public final double angle;

  ArmState(double angle) {
    this.angle = angle;
  }

  ArmState(ArmState other) {
    this(other.angle);
  }
}
