package frc.robot.arm;

public enum ArmState {
  UNTUNED(0),

  CORAL_STOWED(33.0),
  ALGAE_STOWED(40.0),
  UNJAM(UNTUNED),
  PRE_MATCH_HOMING(0.0),
  MID_MATCH_HOMING(0.0),

  CORAL_SCORE_PLACING_L1(0.0),
  CORAL_SCORE_RELEASE_L1(0.0),

  // Centered coral positions
  CORAL_SCORE_CENTERED_LINEUP_L2(24.0),
  CORAL_SCORE_CENTERED_PLACING_L2(9.0),
  CORAL_SCORE_CENTERED_RELEASE_L2(4.0),

  CORAL_SCORE_CENTERED_LINEUP_L3(24.0),
  CORAL_SCORE_CENTERED_PLACING_L3(11.5),
  CORAL_SCORE_CENTERED_RELEASE_L3(4.0),

  CORAL_SCORE_CENTERED_LINEUP_L4(8.0),
  CORAL_SCORE_CENTERED_PLACING_L4(0.0),
  CORAL_SCORE_CENTERED_RELEASE_L4(0.0),

  // Displaced coral positions
  CORAL_SCORE_DISPLACED_LINEUP_L2(15.0),
  CORAL_SCORE_DISPLACED_PLACING_L2(4.0),
  CORAL_SCORE_DISPLACED_RELEASE_L2(0.0),

  CORAL_SCORE_DISPLACED_LINEUP_L3(15.0),
  CORAL_SCORE_DISPLACED_PLACING_L3(4.0),
  CORAL_SCORE_DISPLACED_RELEASE_L3(0.0),

  CORAL_SCORE_DISPLACED_LINEUP_L4(5.0),
  CORAL_SCORE_DISPLACED_PLACING_L4(0.0),
  CORAL_SCORE_DISPLACED_RELEASE_L4(0.0),

  ALGAE_INTAKE_L2(15.0),
  ALGAE_INTAKE_L3(16.0),

  ALGAE_FORWARD_NET(50),
  ALGAE_BACKWARD_NET(100),
  ALGAE_PROCESSOR(-10.0),

  UPRIGHT_CORAL_INTAKE(-41.4),
  GROUND_CORAL_INTAKE(-56.4),
  GROUND_ALGAE_INTAKE(-54.0),

  INTAKING_CORAL_STATION_BACK(146.78), // 128.76
  INTAKING_CORAL_STATION_FRONT(50),

  COLLISION_AVOIDANCE(0.0),
  CLIMBING(60.0),

  SMART_STOW_1(100.0);

  public final double angle;

  ArmState(double angle) {
    this.angle = angle;
  }

  ArmState(ArmState other) {
    this(other.angle);
  }
}
