package frc.robot.swerve;

public enum SwerveState {
  TELEOP,
  TELEOP_SNAPS,
  AUTO,
  AUTO_SNAPS,
  INTAKE_ASSIST_CORAL_TELEOP,
  PURPLE_ALIGN_AUTO,
  PURPLE_ALIGN_TELEOP,
  INTAKE_ASSIST_ALGAE_TELEOP,
  REEF_MAGNETISM_TELEOP;
}
