package frc.robot.swerve;

public enum SwerveState {
  TELEOP,
  TELEOP_SNAPS,
  AUTO,
  AUTO_SNAPS,
  INTAKE_ASSIST_CORAL_TELEOP,
  INTAKE_ASSIST_CORAL_AUTO,
  INTAKE_ASSIST_ALGAE_TELEOP,
  INTAKE_ASSIST_ALGAE_AUTO,
  SCORE_ASSIST,
  PURPLE_ALIGN;
}
