package frc.robot.elevator;

public enum ElevatorState {
  UNTUNED(0.0),
  UNJAM(UNTUNED),
  REHOME(UNTUNED),

  ALGAE_INTAKE_GROUND(UNTUNED),
  ALGAE_INTAKE_L2(UNTUNED),
  ALGAE_INTAKE_L3(UNTUNED),

  ALGAE_NET(UNTUNED),
  PROCESSOR(UNTUNED),
  ALGAE_OUTTAKE(UNTUNED),

  STOWED(UNTUNED),
  STOWED_INWARD(UNTUNED),
  PRE_CORAL_HANDOFF(UNTUNED),
  HANDOFF(UNTUNED),

  L1_SCORE_LINEUP(UNTUNED),
  L1_SCORE_RELEASE(UNTUNED),

  L2_SCORE_LINEUP(UNTUNED),
  L2_SCORE_RELEASE(UNTUNED),

  L3_SCORE_LINEUP(UNTUNED),
  L3_SCORE_RELEASE(UNTUNED),

  L4_SCORE_LINEUP(UNTUNED),
  L4_SCORE_RELEASE(UNTUNED),

  CLIMBING(UNTUNED),
  LOLLIPOP_CORAL_INTAKE_INTAKE(UNTUNED),
  LOLLIPOP_CORAL_INTAKE_PUSH(UNTUNED);

  public final double height;

  private ElevatorState(double height) {
    this.height = height;
  }

  private ElevatorState(ElevatorState state) {
    this.height = state.height;
  }
}
