package frc.robot.robot_manager;

public enum RobotState {
  IDLE_NO_GP,
  IDLE_ALGAE,
  IDLE_CORAL,

  INTAKE_ALGAE_FLOOR,
  INTAKE_ALGAE_L2,
  INTAKE_ALGAE_L3,

  INTAKE_STATION_APPROACH,
  INTAKE_CORAL_STATION_BACK,
  INTAKE_CORAL_STATION_FRONT,
  SMART_STOW_1,
  SMART_STOW_2,

  INTAKE_CORAL_FLOOR_UPRIGHT,
  INTAKE_CORAL_FLOOR_HORIZONTAL,
  INTAKE_ASSIST_CORAL_FLOOR_HORIZONTAL,

  ALGAE_OUTTAKE,

  PROCESSOR_WAITING,
  PROCESSOR_PREPARE_TO_SCORE,
  PROCESSOR_SCORING,

  NET_FORWARD_WAITING,
  NET_FORWARD_PREPARE_TO_SCORE,
  NET_FORWARD_SCORING,

  NET_BACK_WAITING,
  NET_BACK_PREPARE_TO_SCORE,
  NET_BACK_SCORING,

  // Aproaching coral states
  CORAL_L2_1_APPROACH,
  CORAL_L3_1_APPROACH,
  CORAL_L4_1_APPROACH,

  // L1 scoring has no LINEUP, APPROACH state, or CENTERED/DISPLACED versions since it's so simple
  // to score
  CORAL_L1_3_PLACE,
  CORAL_L1_4_RELEASE,

  // Centered coral states
  CORAL_CENTERED_L2_2_LINEUP,
  CORAL_CENTERED_L2_3_PLACE,
  CORAL_CENTERED_L2_4_RELEASE,

  CORAL_CENTERED_L3_2_LINEUP,
  CORAL_CENTERED_L3_3_PLACE,
  CORAL_CENTERED_L3_4_RELEASE,

  CORAL_CENTERED_L4_1_POINT_5_RAISE_ARM,
  CORAL_CENTERED_L4_2_LINEUP,
  CORAL_CENTERED_L4_3_PLACE,
  CORAL_CENTERED_L4_3_PLACE_THEN_RELEASE,
  CORAL_CENTERED_L4_4_RELEASE,

  // Displaced coral states
  CORAL_DISPLACED_L2_2_LINEUP,
  CORAL_DISPLACED_L2_3_PLACE,
  CORAL_DISPLACED_L2_4_RELEASE,

  CORAL_DISPLACED_L3_2_LINEUP,
  CORAL_DISPLACED_L3_3_PLACE,
  CORAL_DISPLACED_L3_4_RELEASE,

  CORAL_DISPLACED_L4_1_POINT_5_RAISE_ARM,
  CORAL_DISPLACED_L4_2_LINEUP,
  CORAL_DISPLACED_L4_3_PLACE,
  CORAL_DISPLACED_L4_3_PLACE_THEN_RELEASE,
  CORAL_DISPLACED_L4_4_RELEASE,

  CLIMBING_1_LINEUP,
  CLIMBING_2_HANGING,
  CLIMBING_3_HANGING_2,
  CLIMBING_4_HANGING_3,

  UNJAM,
  PREPARE_UNJAM_CORAL_STATION,
  UNJAM_CORAL_STATION,

  REHOME_ELEVATOR,
  REHOME_ARM,
  REHOME_ROLL;
}
