package frc.robot.robot_manager;

public enum RobotState {
  IDLE_NO_GP,
  IDLE_ALGAE,
  IDLE_CORAL,

  INTAKE_ALGAE_FLOOR,
  INTAKE_ALGAE_L2,
  INTAKE_ALGAE_L3,

  DISLODGE_ALGAE_L2_WAIT,
  DISLODGE_ALGAE_L3_WAIT,
  DISLODGE_ALGAE_L2_PUSHING,
  DISLODGE_ALGAE_L3_PUSHING,

  PRE_INTAKE_CORAL_STATION,
  AFTER_INTAKE_CORAL_STATION,

  INTAKE_CORAL_STATION,
  INTAKE_CORAL_FLOOR_UPRIGHT,
  INTAKE_CORAL_FLOOR_HORIZONTAL,

  PROCESSOR_WAITING,
  PROCESSOR_PREPARE_TO_SCORE,
  PROCESSOR_SCORING,

  NET_FORWARD_WAITING,
  NET_FORWARD_PREPARE_TO_SCORE,
  NET_FORWARD_SCORING,

  PRE_NET_BACK_WAITING,
  AFTER_NET_BACK_WAITING,
  NET_BACK_WAITING,
  NET_BACK_PREPARE_TO_SCORE,
  NET_BACK_SCORING,

  CORAL_L1_1_APPROACH,
  CORAL_L1_2_LINEUP,
  CORAL_L1_3_PLACE,
  CORAL_L1_4_RELEASE,

  CORAL_L2_1_APPROACH,
  CORAL_L2_2_LINEUP,
  CORAL_L2_3_PLACE,
  CORAL_L2_4_RELEASE,

  CORAL_L3_1_APPROACH,
  CORAL_L3_2_LINEUP,
  CORAL_L3_3_PLACE,
  CORAL_L3_4_RELEASE,

  CORAL_L4_1_APPROACH,
  CORAL_L4_2_LINEUP,
  CORAL_L4_3_PLACE,
  CORAL_L4_3_PLACE_THEN_RELEASE,
  CORAL_L4_4_RELEASE,

  CLIMBING_1_LINEUP,
  CLIMBING_2_HANGING,

  UNJAM,

  REHOME_ELEVATOR,
  REHOME_WRIST,
  REHOME_ROLL;
}
