package frc.robot.claw;

public enum ClawState {
  IDLE_NO_GP,
  IDLE_W_ALGAE,
  IDLE_W_CORAL,
  INTAKING_ALGAE,
  CORAL_HANDOFF,
  SCORE_ALGAE_NET,
  SCORE_ALGAE_PROCESSOR,
  SCORE_CORAL,
  OUTTAKING,
  TRUFFLA_CORAL_INTAKE;
}
