package frc.robot.claw;

public enum ClawState {
  IDLE_NO_GP,
  IDLE_W_ALGAE,
  IDLE_W_CORAL,
  INTAKING_ALGAE,
  INTAKING_CORAL,
  SCORE_ALGAE_NET_FORWARD,
  SCORE_ALGAE_NET_BACK,
  SCORE_ALGAE_PROCESSOR,
  SCORE_CORAL,
  OUTTAKING;
}
